"""Recordings API endpoints — browse, stream, export recordings."""

from __future__ import annotations

import os
import uuid
from datetime import datetime
from typing import Annotated

import structlog
from fastapi import APIRouter, Depends, Header, HTTPException, Query, status
from fastapi.responses import FileResponse, Response, StreamingResponse
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from ...core.database import get_db
from ...middleware.auth import get_current_user, require_admin, require_operator
from ...services.recording_service import (
    bulk_delete_recordings,
    delete_recording,
    get_recording,
    get_recording_stats,
    get_timeline_segments,
    list_recordings,
)

logger = structlog.get_logger()
router = APIRouter(prefix="/api/v1/recordings", tags=["recordings"])


@router.get("")
async def get_recordings(
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
    page: int = Query(1, ge=1),
    per_page: int = Query(25, ge=1, le=100),
    camera_id: uuid.UUID | None = None,
    recording_type: str | None = None,
    from_time: str | None = None,
    to_time: str | None = None,
):
    return await list_recordings(
        db,
        page=page,
        per_page=per_page,
        camera_id=camera_id,
        recording_type=recording_type,
        from_time=from_time,
        to_time=to_time,
    )


@router.get("/timeline")
async def get_timeline(
    camera_id: uuid.UUID,
    date: str,
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    segments = await get_timeline_segments(camera_id, date, db)
    return {"data": segments}


@router.get("/stats")
async def get_stats(
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    return {"data": await get_recording_stats(db)}


@router.get("/{recording_id}")
async def get_recording_by_id(
    recording_id: uuid.UUID,
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    recording = await get_recording(recording_id, db)
    return {"data": recording}


@router.get("/{recording_id}/thumbnail")
async def thumbnail_recording(
    recording_id: uuid.UUID,
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    """Serve the sidecar JPEG thumbnail generated by the recording engine."""
    recording = await get_recording(recording_id, db)
    thumb = os.path.splitext(recording.file_path)[0] + ".jpg"
    if not os.path.exists(thumb):
        raise HTTPException(status_code=404, detail="Thumbnail not available")
    return FileResponse(thumb, media_type="image/jpeg", headers={"Cache-Control": "max-age=3600"})


class BulkDeleteRequest(BaseModel):
    ids: list[uuid.UUID] | None = None
    delete_all: bool = False
    before: datetime | None = None
    camera_id: uuid.UUID | None = None


@router.post("/bulk-delete")
async def bulk_delete(
    body: BulkDeleteRequest,
    current_user: Annotated[dict, Depends(require_operator)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    """Bulk delete recordings: by id list, all (optionally per camera), or before a date."""
    if not body.ids and not body.delete_all and body.before is None:
        raise HTTPException(
            status_code=400,
            detail="Provide ids, delete_all=true, or a before date",
        )
    result = await bulk_delete_recordings(
        db,
        ids=body.ids,
        delete_all=body.delete_all,
        before=body.before,
        camera_id=body.camera_id,
    )
    return {"data": result}


@router.get("/{recording_id}/stream")
async def stream_recording(
    recording_id: uuid.UUID,
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
    range: Annotated[str | None, Header()] = None,
    download: bool = Query(False),
):
    """Stream a recording with HTTP Range support (seekable playback).

    Set ?download=true to force Content-Disposition: attachment.
    """
    recording = await get_recording(recording_id, db)
    file_path = recording.file_path
    if not file_path or not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Recording file not found on disk")

    file_size = os.path.getsize(file_path)
    start, end = _parse_range(range, file_size)

    ts = recording.start_time.strftime("%Y-%m-%d_%H%M%S") if recording.start_time else str(recording_id)[:8]
    filename = f"recording_{recording.camera_id}_{ts}.mp4" if hasattr(recording, "camera_id") else f"recording_{recording_id}.mp4"

    def file_iterator(path: str, offset: int, remaining: int, chunk_size: int = 1024 * 1024):
        with open(path, "rb") as f:
            f.seek(offset)
            left = remaining
            while left > 0:
                chunk = f.read(min(chunk_size, left))
                if not chunk:
                    break
                left -= len(chunk)
                yield chunk

    headers = {"Accept-Ranges": "bytes"}
    if download:
        headers["Content-Disposition"] = f'attachment; filename="{filename}"'

    is_full_range = (start == 0 and end == file_size - 1)

    if range and not is_full_range:
        return StreamingResponse(
            file_iterator(file_path, start, end - start + 1),
            status_code=206,
            media_type="video/mp4",
            headers={
                 **headers,
                "Content-Length": str(end - start + 1),
                "Content-Range": f"bytes {start}-{end}/{file_size}",
            },
         )

    return StreamingResponse(
        file_iterator(file_path, 0, file_size),
        media_type="video/mp4",
        headers={**headers, "Content-Length": str(file_size)},
     )


@router.head("/{recording_id}/stream")
async def head_stream(
    recording_id: uuid.UUID,
    current_user: Annotated[dict, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    """Return headers for a recording stream without the body (browser pre-flight)."""
    recording = await get_recording(recording_id, db)
    file_path = recording.file_path
    if not file_path or not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Recording file not found on disk")
    file_size = os.path.getsize(file_path)
    headers = {
        "Accept-Ranges": "bytes",
        "Content-Length": str(file_size),
        "Content-Type": "video/mp4",
    }
    return Response(headers=headers)


def _parse_range(range_header: str | None, file_size: int) -> tuple[int, int]:
    """Parse 'bytes=start-end' into absolute (start, end), clamped."""
    if not range_header or not range_header.startswith("bytes="):
        return 0, file_size - 1
    try:
        spec = range_header[6:].split(",")[0]
        start_s, end_s = spec.split("-")
        if start_s == "":
            # suffix range: last N bytes
            length = int(end_s)
            return max(0, file_size - length), file_size - 1
        start = int(start_s)
        end = int(end_s) if end_s else file_size - 1
        return min(start, file_size - 1), min(end, file_size - 1)
    except (ValueError, IndexError):
        return 0, file_size - 1


@router.delete("/{recording_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_recording_by_id(
    recording_id: uuid.UUID,
    current_user: Annotated[dict, Depends(require_admin)],
    db: Annotated[AsyncSession, Depends(get_db)],
):
    await delete_recording(recording_id, db)
