#!/usr/bin/env bash
# ============================================================================
# NVR System — Pre-commit & Post-commit Hook Setup
# ============================================================================
# Installs git hooks for:
#   1. Secret scanning (gitleaks)
#   2. Container naming guard (nvr- prefix)
#   3. File line count check (≤500 lines)
#   4. Post-commit auto version tag (v0.00.XX-<hash>)
# ============================================================================
set -euo pipefail

HOOK_DIR="$(git rev-parse --git-dir)/hooks"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

echo "=== NVR System Hook Setup ==="
echo "Git hooks directory: ${HOOK_DIR}"
echo ""

# ---------- Check dependencies ----------
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "WARNING: '$1' not found — related hook will be skipped."
        return 1
    fi
    return 0
}

check_cmd gitleaks
check_cmd python3

# ---------- Pre-commit Hook ----------
echo "Installing pre-commit hook..."

cat > "${HOOK_DIR}/pre-commit" << 'PRE_COMMIT_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-hooks.sh
set -euo pipefail

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
ERRORS=0

echo ""
echo "=== NVR Pre-commit Checks ==="

# ── 1. Secret Scan ──────────────────────────────────────────
echo -n "[1/3] Secret scan (gitleaks)... "
if command -v gitleaks &>/dev/null; then
    if gitleaks detect --no-git --source="${PROJECT_ROOT}" --exit-code=0 2>&1 > /dev/null; then
        leaks=$(gitleaks detect --no-git --source="${PROJECT_ROOT}" --exit-code=0 2>&1 | grep -c "Finding" || true)
        if [ "${leaks}" -gt 0 ]; then
            echo "FAILED (${leaks} secrets found!)"
            gitleaks detect --no-git --source="${PROJECT_ROOT}" --exit-code=0 2>&1 | grep "Finding" || true
            ERRORS=$((ERRORS + 1))
        else
            echo "OK"
        fi
    else
        echo "OK"
    fi
else
    echo "SKIPPED (gitleaks not installed)"
fi

# ── 2. Container Naming Guard ───────────────────────────────
echo -n "[2/3] Container naming (nvr- prefix)... "

# Only check staged docker-compose files
violations=""
for f in $(git diff --cached --name-only --diff-filter=ACM | grep -E 'docker-compose.*\.ya?ml$' || true); do
    if [ -f "${PROJECT_ROOT}/${f}" ]; then
        # Check container_name values
        bad_names=$(grep -E 'container_name:\s*(?!nvr-)[a-zA-Z]' "${PROJECT_ROOT}/${f}" || true)
        if [ -n "${bad_names}" ]; then
            violations="${violations}${f}:\n${bad_names}\n\n"
        fi
    fi
done

if [ -n "${violations}" ]; then
    echo "FAILED"
    echo -e "Container names MUST start with 'nvr-':\n${violations}"
    ERRORS=$((ERRORS + 1))
else
    echo "OK"
fi

# ── 3. File Line Count ──────────────────────────────────────
echo -n "[3/3] File line count (≤500)... "

overlong=""
for f in $(git diff --cached --name-only --diff-filter=A | grep -E '\.(py|ts|tsx|sql)$' || true); do
    if [ -f "${PROJECT_ROOT}/${f}" ]; then
        lines=$(wc -l < "${PROJECT_ROOT}/${f}")
        if [ "${lines}" -gt 500 ]; then
            overlong="${overlong}  ${f}: ${lines} lines\n"
        fi
    fi
done

if [ -n "${overlong}" ]; then
    echo "FAILED"
    echo -e "Files exceed 500 line limit:\n${overlong}"
    echo "Split large files before committing. See AGENTS.md §16."
    ERRORS=$((ERRORS + 1))
else
    echo "OK"
fi

# ── Result ──────────────────────────────────────────────────
echo "=================================="
if [ "${ERRORS}" -gt 0 ]; then
    echo "Pre-commit checks FAILED (${ERRORS} error(s)). Commit aborted."
    exit 1
else
    echo "Pre-commit checks PASSED."
fi
PRE_COMMIT_EOF

chmod +x "${HOOK_DIR}/pre-commit"
echo "  ✅ pre-commit hook installed"

# ---------- Post-commit Hook (Auto Version Tag) ----------
echo "Installing post-commit hook..."

cat > "${HOOK_DIR}/post-commit" << 'POST_COMMIT_EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/setup-hooks.sh
# Auto-creates version tag after each commit.
# Skip with: git commit -m "[skip-tag] your message"

set -euo pipefail

# Check if commit message contains [skip-tag]
COMMIT_MSG=$(git log -1 --format=%s)
if echo "${COMMIT_MSG}" | grep -qE '\[skip-tag\]|\[no-tag\]'; then
    echo "[post-commit] Tag skipped (commit message says so)."
    exit 0
fi

SHORT_HASH=$(git rev-parse --short=7 HEAD)

# Read current version from pyproject.toml
PROJECT_ROOT=$(git rev-parse --show-toplevel)
PYPROJECT="${PROJECT_ROOT}/pyproject.toml"

if [ -f "${PYPROJECT}" ]; then
    VERSION=$(grep -E '^version\s*=' "${PYPROJECT}" | head -1 | sed 's/version\s*=\s*"\(.*\)"/\1/')
else
    VERSION="0.00.00"
    echo "[post-commit] WARNING: pyproject.toml not found, using default version ${VERSION}"
fi

TAG="v${VERSION}-${SHORT_HASH}"

# Check if tag already exists
if git tag -l | grep -q "^${TAG}$"; then
    echo "[post-commit] Tag ${TAG} already exists. Skipping."
    exit 0
fi

# Create tag
git tag -a "${TAG}" -m "${COMMIT_MSG}"
echo "[post-commit] Tag created: ${TAG}"
POST_COMMIT_EOF

chmod +x "${HOOK_DIR}/post-commit"
echo "  ✅ post-commit hook installed"

echo ""
echo "=== Hook Setup Complete ==="
echo "Pre-commit checks: secret-scan, naming-guard, line-count"
echo "Post-commit action: auto version tag (v<version>-<hash>)"
echo ""
echo "To skip tag on a specific commit:"
echo "  git commit -m '[skip-tag] your message'"
echo ""
echo "To bypass all hooks (emergency only):"
echo "  git commit --no-verify -m 'message'"
